### ISSUE TITLE
Build xcratch on linux platform

### ISSUE THREAD

**Issue by markakis-sch** [xcratch/xcratch.github.io#1]
I have successfully build Scratch 3 on Ubuntu Linux (see [comment](https://github.com/LLK/scratch-desktop/issues/117#issuecomment-964544549) on issue 117 of LLK/scratch-desktop) and i have [publish](https://github.com/markakis-sch/scratch-desktop/releases/) the packages for anyone interested in using them.

I would like to ask if something like this can be done with the xcratch and how. My goal is to be able to use the xcratch along with the [Lego Spike extensions](https://github.com/bricklife/scratch-lego-bluetooth-extensions) in a school lab.

Thanks in advance.

**Comment by yokobond** [comment]
Xcratch is just Scratch with the added ability to load extensions, so I think it can be built in the same way as scratch-desktop.

The changes are separated in the feature/* branches of xcratch/scratch-gui and xcratch/scratch-vm, so you can merge them into the scratch-desktop branch of LLK/scratch-*.

For Bluetooth, by the way, Scratch-Link by LLK is not provided, so you will need an alternative tool such as [kawasaki/pyscrlink: Scratch\-link for Linux written in python](https://github.com/kawasaki/pyscrlink).
